architectures: &Arch
  model:
    select: 'ResidualOnly'
    ResidualOnly:
      name: 'ResidualOnly'
      module: 'custom.model.residual_cnn'
      kwargs:
        hidden_size: 1024
        output_size: &N 8

  optimizer:
    select: 'AdamW'
    AdamW:
      name: 'AdamW'
      module: 'torch.optim'
      kwargs:
        lr: 0.0001
        amsgrad: True

  scheduler:
    select: 'CyclicLR'
    CyclicLR: &CyclicalLR_args
      name: 'CyclicLR'
      module: 'torch.optim.lr_scheduler'
      kwargs:
        base_lr: 0.0001
        max_lr: 0.002
        step_size_up: 1000
        step_size_down: 9000
        mode: 'triangular2'
        cycle_momentum: False
    LinearLR1: &LinearLR1_args
      name: 'LinearLR'
      module: 'torch.optim.lr_scheduler'
      kwargs:
        total_iters: 10000
    LinearLR2: &LinearLR2_args
      name: 'LinearLR'
      module: 'torch.optim.lr_scheduler'
      kwargs:
        total_iters: 90000
    MySequentialLR:
      name: 'MySequentialLR'
      module: 'custom.scheduler.sequential_lr'
      kwargs:
        schedulers:
          - *LinearLR1_args
          - *LinearLR2_args

  loss:
    select: 'MyCrossEntropyLoss'
    MyCrossEntropyLoss:
      name: 'MyCrossEntropyLoss'
      module: 'custom.loss.cross_entropy'
      kwargs:
        weight: [0.25, 0.61, 0.38, 0.017, 6.5, 0.044, 0.13, 0.061]

  metric:
    select:
      - 'MulticlassAccuracy'
    use_loss: True
    MulticlassAccuracy:
      name: 'MulticlassAccuracy'
      module: 'torchmetrics.classification'
      kwargs:
        num_classes: *N
        average: 'macro'
        top_k: 1


data:
  dataloaders:
    train_loader:
      kwargs:
        batch_size: 256
        shuffle: True
        pin_memory: True
        num_workers: 4
      dataset: 'trainDataset2201_2306'
    valid_loader:
      kwargs:
        batch_size: 1
        shuffle: False
        pin_memory: True
        num_workers: 4
      dataset: 'validDataset2201_2306'

  datasets:
    trainDataset2201_2306:
      name: 'MergeDataset'
      module: 'custom.dataset.merge_dataset'
      kwargs:
        module: 'custom.dataset.image_dataset'
        name: 'ImageCsvDataset'
        kwargs_list:
          - dataset_path: './data/processed/20231205/2022-01/split-train.csv'
          - dataset_path: './data/processed/20231205/2022-02/split-train.csv'
          - dataset_path: './data/processed/20231205/2022-03/split-train.csv'
          - dataset_path: './data/processed/20231205/2022-04/split-train.csv'
          - dataset_path: './data/processed/20231205/2022-05/split-train.csv'
          - dataset_path: './data/processed/20231205/2022-06/split-train.csv'
          - dataset_path: './data/processed/20231205/2022-07/split-train.csv'
          - dataset_path: './data/processed/20231205/2022-08/split-train.csv'
          - dataset_path: './data/processed/20231205/2022-09/split-train.csv'
          - dataset_path: './data/processed/20231205/2022-10/split-train.csv'
          - dataset_path: './data/processed/20231205/2022-11/split-train.csv'
          - dataset_path: './data/processed/20231205/2022-12/split-train.csv'
          - dataset_path: './data/processed/20231205/2023-01/split-train.csv'
          - dataset_path: './data/processed/20231205/2023-02/split-train.csv'
          - dataset_path: './data/processed/20231205/2023-03/split-train.csv'
          - dataset_path: './data/processed/20231205/2023-04/split-train.csv'
          - dataset_path: './data/processed/20231205/2023-05/split-train.csv'
          - dataset_path: './data/processed/20231205/2023-06/split-train.csv'

    validDataset2201_2306:
      name: 'MergeDataset'
      module: 'custom.dataset.merge_dataset'
      kwargs:
        module: 'custom.dataset.image_dataset'
        name: 'ImageCsvDataset'
        kwargs_list:
          - {dataset_path: './data/processed/20231205/2022-01/split-valid.csv', apply_augment: False}
          - {dataset_path: './data/processed/20231205/2022-02/split-valid.csv', apply_augment: False}
          - {dataset_path: './data/processed/20231205/2022-03/split-valid.csv', apply_augment: False}
          - {dataset_path: './data/processed/20231205/2022-04/split-valid.csv', apply_augment: False}
          - {dataset_path: './data/processed/20231205/2022-05/split-valid.csv', apply_augment: False}
          - {dataset_path: './data/processed/20231205/2022-06/split-valid.csv', apply_augment: False}
          - {dataset_path: './data/processed/20231205/2022-07/split-valid.csv', apply_augment: False}
          - {dataset_path: './data/processed/20231205/2022-08/split-valid.csv', apply_augment: False}
          - {dataset_path: './data/processed/20231205/2022-09/split-valid.csv', apply_augment: False}
          - {dataset_path: './data/processed/20231205/2022-10/split-valid.csv', apply_augment: False}
          - {dataset_path: './data/processed/20231205/2022-11/split-valid.csv', apply_augment: False}
          - {dataset_path: './data/processed/20231205/2022-12/split-valid.csv', apply_augment: False}
          - {dataset_path: './data/processed/20231205/2023-01/split-valid.csv', apply_augment: False}
          - {dataset_path: './data/processed/20231205/2023-02/split-valid.csv', apply_augment: False}
          - {dataset_path: './data/processed/20231205/2023-03/split-valid.csv', apply_augment: False}
          - {dataset_path: './data/processed/20231205/2023-04/split-valid.csv', apply_augment: False}
          - {dataset_path: './data/processed/20231205/2023-05/split-valid.csv', apply_augment: False}
          - {dataset_path: './data/processed/20231205/2023-06/split-valid.csv', apply_augment: False}


runner:
  step_mod: 'grad'
  total_steps: 100000
  log_freq: 100
  dev_freq: 1000
  save_freq: 500
  trainer_kwargs:
    gradient_accumulation_steps: 1
  valider_kwargs: {}


ckpt:
  save_mod : 'max'
  check_metrics:
    - 'MulticlassAccuracy'
  ckpt_dir: ~  # default: './results/{name}'
  keep_num: 3


WandB:
  project: &P 'NewEarthWork'
  init_kwargs:
    config: *Arch
  watch_kwargs:
    log: 'all'
    log_freq: 1000

