architectures: &Arch
  model:
    select: 'ResidualOnly'
    ResidualOnly:
      module: 'custom.model.residual_cnn'
      args:
        hidden_size: 256
        output_size: &N 8

  optimizer:
    select: 'AdamW'
    AdamW: &AdamW_args
      module: 'torch.optim'
      args:
        lr: 0.0003
    Adam: *AdamW_args

  scheduler:
    select: 'ConstantLR'
    ExponentialLR:
      module: 'torch.optim.lr_scheduler'
      args:
        gamma: 0.9995
    ConstantLR:
      module: 'torch.optim.lr_scheduler'
      args:
        total_iters: 0

  loss:
    select: 'CrossEntropyLoss'
    CrossEntropyLoss:
      module: 'torch.nn'
      args: {}

  metric:
    select:
      - 'MulticlassAccuracy'
    use_loss: True
    MulticlassAccuracy:
      module: 'torchmetrics.classification'
      args:
        num_classes: *N
        average: 'macro'


data:
  train_loader:
    dataset:
      select: 'ImageCsvDataset'
      ImageCsvDataset:
        module: 'custom.dataset.image_dataset'
        args:
          dataset_path: './data/processed/20231205/2023-07/split-train.csv'
    args:
      batch_size: 64
      shuffle: True
      pin_memory: True
      num_workers: 0

  valid_loader:
    dataset:
      select: 'ImageCsvDataset'
      ImageCsvDataset:
        module: 'custom.dataset.image_dataset'
        args:
          dataset_path: './data/processed/20231205/2023-07/split-valid.csv'
    args:
      batch_size: 1
      shuffle: False
      pin_memory: True
      num_workers: 0


runner:
  step_mod: 'grad'
  total_steps: 10000
  log_freq: 100
  dev_freq: 1000
  save_freq: 500
  init_args:
    gradient_accumulation_steps: 1


ckpt:
  save_mod : 'max'
  check_metrics:
    - 'MulticlassAccuracy'
  ckpt_dir: ~  # default: './data/saved_models/{name}'
  keep_num: 3


WandB:
  project: &P 'Template_project'
  init_args:
    name: 'Template_model'
    config: *Arch
  watch_args:
    log: 'all'
    log_freq: 1000
  sweep:
    num_trials: 30
    config:
      name: 'Template_sweep'
      method: 'random'
      metric:
        name: 'Valid_loss'
        goal: 'minimize'
      parameters:
        runner:
          parameters:
            total_steps:
              value: 100
            log_freq:
              value: 50
            dev_freq:
              value: 50
        architectures:
          parameters:
            optimizer:
              parameters:
                select:
                  values:
                    - 'AdamW'
                    - 'Adam'
                AdamW:
                  parameters:
                    args:
                      parameters:
                        lr:
                          values:
                            - 0.0001
                            - 0.0003
                            - 0.0005
        data:
          parameters:
            train_loader:
              parameters:
                args:
                  parameters:
                    batch_size:
                      values:
                        - 16
                        - 32
                        - 64

